name: endtest(Netlify)
#on:
#  workflow_dispatch:
#  pull_request:
#    branches: [master] #You would need to make sure this is correct every time
on:
  workflow_dispatch:
  push: 

jobs:
  wait_for_netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for netlify preview (60 seconds)
        uses: JakePartusch/wait-for-netlify-action@v1.4 #Documentation: https://github.com/marketplace/actions/wait-for-netlify
        with: 
          site_name: "gentle-dolphin-a02324" # this becomes "https://{site_name}.netlify.app"
          max_timeout: 60
  run_test_case:
    name: Run test case and check for errors
    runs-on: ubuntu-latest
    needs: wait_for_netlify
    steps:
      - uses: actions/checkout@master
      - name: Running EndTest test case(s)
        id: endtest_functional_tests
        uses: endtest-technologies/github-run-tests-action@v1.8
#        env: "not required"
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          app_id: ${{ secrets.EndTest_app_id }}
          app_code: ${{ secrets.EndTest_app_code }}
          api_request: ${{ secrets.EndTest_api_request }}
          number_of_loops: 10
      - name: Check for errors
        run: |
          if [[ ${{ steps.endtest_functional_tests.outputs.errors }} != 0 ]]; then exit 1; else exit 0; fi
          echo "Please review, ${{ steps.endtest_functional_tests.outputs.errors }} error(s) occurred. View results here: ${{ steps.endtest_functional_tests.outputs.results }}"
      - name: Check for failed test cases
        run: |
          if [[ ${{ steps.endtest_functional_tests.outputs.failed }} != 0 ]]; then exit 1; else exit 0; fi
          echo "Please review, ${{ steps.endtest_functional_tests.outputs.failed }} test case(s) failed. View results here: ${{ steps.endtest_functional_tests.outputs.results }}"